[package]
name = "solana-bpf-loader-program"
version = "1.1.11"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"
libc = "0.2.68"
log = "0.4.8"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
<<<<<<< HEAD
solana-logger = { path = "../../logger", version = "1.1.11" }
solana-sdk = { path = "../../sdk", version = "1.1.11" }
solana_rbpf = "=0.1.27"
=======
solana-logger = { path = "../../logger", version = "1.2.0" }
solana-runtime = { path = "../../runtime", version = "1.2.0" }
solana-sdk = { path = "../../sdk", version = "1.2.0" }
solana_rbpf = "=0.1.28"
>>>>>>> 7e364d01c... Bump solana-rbpf to v0.1.28 (#9976)
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
